const fixedProduct = (idnum, name, offerText = "") => ({
  idnum,
  name,
  offerText,
});

const hiddenProductsRaw = [
  
      
fixedProduct(285, "355ML RED BULL GRANDE"),
fixedProduct(287, "ABRILLANTADOR MICAL MAQUINAS 5L"),


fixedProduct(292, "ACEITUNAS OFERTA SIN HUESO UNIDAD"),
fixedProduct(293, "ACOND ANIAN NATURAL 1000"),
fixedProduct(294, "AGRIO DE LIMON GOURMET 1/2"),
fixedProduct(296, "AGUA DESIONIZADA 2L KIRIKO"),
fixedProduct(297, "AGUA FONT VELLA 1.5 L"),

fixedProduct(300, "AGUA LANJARON 0,75L 15 UNID."),


fixedProduct(303, "AGUA OXIGENADA KELSIA 250"),


fixedProduct(306, "AJO GRANULADO LA BARRACA BTE PEQUEÑO"),
fixedProduct(307, "AJONJOLI DORADO LA BARRACA BTE PEQUEÑO"),
fixedProduct(308, "AJO PEREJIL LA BARRACA BTE PEQUEÑO"),
fixedProduct(309, "ALBAHACA BARRACA BTE PEQUEÑO"),

fixedProduct(312, "ALBONDIGAS LOURIÑO L/425"),

fixedProduct(314, "ALCOHOL MICADERM SANITARIO 250 ML"),


fixedProduct(317, "ALUBIAS BLANCA 1/2 KG"),


fixedProduct(322, "AMONIACO PQS 1 L."),
fixedProduct(323, "ANCHOAS CAPRIMAR ABRE F."),
fixedProduct(326, "ANIS ARENA SECO 1 L."),
fixedProduct(328, "APETINAS KETCHUP 25G"),
fixedProduct(329, "APETINAS KETCHUP 90G"),

fixedProduct(333, "ARIEL LIQ 28D"),
fixedProduct(335, "ARROZ BRILLANTE BASMATI 2X125 GR"),

fixedProduct(337, "ARROZ SOS 1/2"),

fixedProduct(339, "ATUN PESCAMAR TOMATE RO-80 AF"),
fixedProduct(340, "ATUN RAZO AC/VEG. PACK 3 ABREFACIL","Por 4 unidades REGALO 1 unidad"),
fixedProduct(341, "AVECREM PESCADO 8 PASTILLAS"),
fixedProduct(342, "AVECREM POLLO 8"),
fixedProduct(344, "AZUCAR AZUCARERA MORENO PPC 800G"),
fixedProduct(345, "AZUCAR SOBRES 10GR CONSEMUR"),



fixedProduct(353, "BANDERILLA GOURMET PICA.150G"),
fixedProduct(354, "BASTONCILLOS ALGODON COALIMENT 200UDS"),
fixedProduct(358, "BAYETA MICAL 1 UNIDAD MICRIFI 38X40"),
fixedProduct(359, "BAYETA MICAL AMARILLA 40X36 CM 10U"),
fixedProduct(360, "BAYETA MICAL MICROFIBRA BAÑO 38X40 2U"),

fixedProduct(363, "BERBERECHO DIAMIR RR-120 70/80"),


fixedProduct(367, "BOL GRANDE"),
fixedProduct(368, "BOL PEQUEÑO"),

fixedProduct(370, "BOLSA 35X50 ASA FINA 200 U CAMISETA"),
fixedProduct(371, "BOLSA BASURA 115X150 SUPER GRANDE CARNICERIA"),

fixedProduct(378, "BOLSAS 10X20 PURUÑUELA"),


fixedProduct(383, "BRANDY MAGNO 70 CL."),
fixedProduct(384, "BROTES DE SOJA GOURMET 180G"),


fixedProduct(388, "CABALLA ACEITE/V UBAGO 90"),
fixedProduct(389, "CABALLA UBAGO TOMATE 90G"),
fixedProduct(390, "CABALLERO GARBANZO LECHOSO 1/2 K"),
fixedProduct(391, "CABALLERO LENTEJA CASTELLANA 1/2 K"),

fixedProduct(393, "CABECERO LOMO VIAN SANA 60G"),

fixedProduct(396, "CAFE FRIO LANDESSA KAKAO"),
fixedProduct(397, "CALAMAR MIAU AMERICANA RO-85P3"),
fixedProduct(398, "CALAMAR MIAU TINTA RO-85P3"),

fixedProduct(401, "CALLOS APIS LT 390 GR"),


fixedProduct(406, "CANELA MOLIDA LA BARRACA"),
fixedProduct(407, "CANELA RAMA LA BARRACA"),


fixedProduct(410, "CASERA BLANCA LATA"),

fixedProduct(441, "CHORIZO Y MORCILLA IBERICOS VACIO 200G"),

fixedProduct(443, "CHURRUCA KIKONAZO PLUS 50 UNID."),
fixedProduct(444, "CHURRUCA PASARRATOS EJECUTIVE 10UDS"),
fixedProduct(445, "CHURRUCA PASARRATOS SENIOR 20UDS"),
fixedProduct(446, "CLAVO GRANO LA BARRACA BTE CRISTAL"),

fixedProduct(451, "COCIDO MADRILEÑO LITORAL 440GR"),
fixedProduct(452, "COCINA FAMADIS LIMON ROLLOM P-2"),
fixedProduct(453, "COCINA NICKY LIMON ROLLO P-2"),

fixedProduct(456, "COLONIA MECADERM INF 750 ML"),
fixedProduct(457, "COLORANTE LA BARRACA"),
fixedProduct(458, "COMIDA GATO MIC&FR.MIX CARNR 4K"),
fixedProduct(459, "COMIDA MIC&FR. PERRO BUEY 300GR"),

fixedProduct(461, "COMIDA PERRO MIC&FRIENDS 4K"),
fixedProduct(462, "COMINO GRANO LA BARRACA B/PEQUEÑO"),
fixedProduct(463, "COMINO MOLIDO LA BARRACA BTE PEQUEÑO"),
fixedProduct(464, "COMP AFECTIVA NOCHE 10U"),

fixedProduct(466, "COMP AFECTIVA ULTRA ALA 16U"),

fixedProduct(468, "COMP. EVAX FINA Y SEGURA NORM 16 U"),

fixedProduct(470, "COMPRESA AFECTIVA ECONOMICA EST.20 UNI"),
fixedProduct(471, "COMPRESA FINA Y SEG.ALAS NORMAL EVAX 12U"),
fixedProduct(472, "CONOS VAINILLA Y CHOCOLATE 4 SOMOSIERRA"),

fixedProduct(474, "CR CACAO NOCILLA 190 DUO"),
fixedProduct(475, "CR CACAO NOCILLA 190 ORIGINAL"),
fixedProduct(476, "CUÑA DE QUESO RESERVA PREC.200 GR.CAMP."),
fixedProduct(477, "CUÑA QUESO CABRA PRECORT.CAMPOF.200 GR"),

fixedProduct(479, "CUBO FREGONA KARIN + ESCURRIDOR"),
fixedProduct(480, "CUBO PESTIÑOS SERAFIN 800 GR"),
fixedProduct(481, "CUCHILLA GILLETE BLUEII 5+1"),
fixedProduct(482, "CURRY BARRACA BOTE CRISTAL PEQUEÑO"),
fixedProduct(483, "C.V ESPUMOSO ROSADO \"MAGNA\""),
fixedProduct(488, "DESOD.DOVE ORIGINAL SP 250ML"),
fixedProduct(489, "DETE LIQ. 5L LUCECITA ORIGINAL KIRIKO 5L"),
fixedProduct(490, "DETE LIQ. LUCECITA AZUL KIRIKO 5L"),
fixedProduct(491, "DETE LIQ. LUCECITA J MARSELLA KIRIKO 5L"),
fixedProduct(493, "DETERGENTE LUCECITA 2.8L ORIGINAL 2.8L"),
fixedProduct(494, "DETERG.LIQ.MARSELLA 2 L.KIRIKO"),
fixedProduct(495, "DETER.LIQ HIGIENIZANTE 3L KIRIKO"),
fixedProduct(496, "DETER.LIQ J.MARSELLA 3L KIRIKO"),
fixedProduct(497, "DULCE MEMBRILLO QUIJOTE 400 GR"),
fixedProduct(498, "EDULCORANTE DOSIF.650 COMP.LA BARRACA"),
fixedProduct(499, "ELIXIR MICADERM MENTA 500 ML"),
fixedProduct(501, "ENERDRINK SANDIA Y UVA"),
fixedProduct(503, "ENERYETI ATOMYC"),
fixedProduct(504, "ENJOY 1/2 L NARANJA"),

fixedProduct(508, "ESPECIAS DE CARACOLES GRANO LA BARRACA"),
fixedProduct(509, "ESPECIAS SURT GRANO LA BARRACA BTE PEQUEÑO"),

fixedProduct(511, "ESP. PINCHOS AMARILLOS LA BARRACA BTE .PEQUEÑO"),
fixedProduct(512, "ESPUMA AFEITAR GILLETE 200ML"),
fixedProduct(513, "ESPUMA PERFE EF GIORGI 200"),
fixedProduct(514, "ESTROPAJO FIBRA VERDE PACK"),
fixedProduct(515, "ESTROPAJO MICAL SALVAUÑAS P-3"),
fixedProduct(516, "ESTROPAJO MITALICO PACK"),

fixedProduct(518, "F1 29G 30U KIT KAT"),

fixedProduct(520, "FAIRY 480"),
fixedProduct(521, "FAIRY MAXI PODER"),


fixedProduct(531, "FILETE CABALLA A/V DIAMIR 1000"),

fixedProduct(534, "FINISH PLLAS TODO EN1 25+25u"),
fixedProduct(535, "FLOTA LIQ 2.69 L 42+10 D A.PLUS BOUQUET"),
fixedProduct(541, "FOLIO"),
fixedProduct(554, "FREGONA MICAL ALGODON"),
fixedProduct(555, "FREGONA MICAL AMARILLA"),
fixedProduct(556, "FREGONA MICAL AZUL"),
fixedProduct(557, "FREGONA MICAL MICROFIBRA"),
fixedProduct(558, "FRESHYETI CANDI PLATANO 500 ML"),
fixedProduct(563, "GALLETA OREO 154 GR"),
fixedProduct(564, "GALLETA OREO MINI 160G"),
fixedProduct(565, "GALLET CHIPS-AHOY MINI 160G"),
fixedProduct(566, "GAMA FVL 1.25L LIMON"),
fixedProduct(568, "GAS KARIN"),
fixedProduct(569, "GEL AF GILLETTE 200 SENS EXISTI"),
fixedProduct(570, "GEL DERMO COALIMENT 750ML"),
fixedProduct(571, "GEL FIJA GIORGI MAX EXT FUERTE 240 N3 NEW"),
fixedProduct(572, "GIGANTONES EJECUTIVO CAJA 10U"),
fixedProduct(573, "GIGANTONES SENIOR 20U"),
fixedProduct(574, "GIGANTONES SUPER SENIOR XXL 10U"),

fixedProduct(576, "GINEBRA BOMBAY SAPHIRE 0.7"),

fixedProduct(579, "GINEBRA RIVES 1 L."),

fixedProduct(582, "GINEBRE BEEFEATER 1 L"),


fixedProduct(586, "GUINDILLA RAMA LA BARRACA B/PEQUEÑO"),
fixedProduct(591, "HABAS BABY GOURMET 425G"),
fixedProduct(592, "HAMBURGUESA BUEY UNIDAD"),

fixedProduct(594, "HARINA DE GARBANZO PANAERAS 500GR"),
fixedProduct(595, "HARINA PANAERAS FREIR 1 K","OFERTA"),
fixedProduct(597, "HARINA PANAERAS REPOSTERIA 1 K.","OFERTA"),
fixedProduct(600, "HIERBAS NATURALES BARRACA 15G"),

fixedProduct(603, "HIGIENIZANTE MULTIUSOS 750 ML/KIRIKO"),
fixedProduct(604, "HUEVOS KINDER INVIERNO UNI"),
fixedProduct(605, "INSECT CASA JARDIN 600 SP ROSAS"),

fixedProduct(609, "JABUGUITO DULCE CABO 200GR"),


fixedProduct(612, "JAMON COCIDO 1ª CON/PIEL EXTRAJUGOSO"),


fixedProduct(616, "JUDIA ANCHA CORTADA ALSUR FRASCO 660 G"),
fixedProduct(617, "JUDIAS C/CHORIZO LOZANO LT 425G"),
fixedProduct(618, "JUDIAS VERDES FINAS ALSUR 660 FCO"),

fixedProduct(620, "JUMPERS MANTEQUILLA"),
fixedProduct(621, "JUMPERS YORK Y QUESO 24 U"),
fixedProduct(622, "KASKYS 120 G"),
fixedProduct(623, "KASKYS 45G"),
fixedProduct(625, "KETCHUP PRIMA 290G"),
fixedProduct(626, "KIKONAZOS SUPER SENIOR XXL 10U"),
fixedProduct(627, "KINDER BUENO CHOCO PACK 10"),
fixedProduct(628, "KINDER BUENO WHITE PACK 10"),
fixedProduct(629, "KINDER HAPPY HIPPO BOLSA 10 U"),
fixedProduct(630, "KIT KAT P-3"),
fixedProduct(641, "LACA NELLY FUERTE 400 ML."),
fixedProduct(642, "LACA NELLY SP NORMAL"),



fixedProduct(653, "LAUREL CAJA CARTON BARRACA 12U."),
fixedProduct(654, "LAVAVAJILLAS MICAL MAQUINAS 5L"),


fixedProduct(657, "LECHE COVAP DESNATADA 1 L."),




fixedProduct(673, "LENTEJAS PARDINA 1/2 K"),
fixedProduct(682, "LIMP. VOLVONE LGHT 750ML"),

fixedProduct(687, "LOMO HORNO A LA PIMIE .PROLONGO 100 G"),


fixedProduct(691, "MACEDONIA VERDURAS ALSUR 660 FCO"),

fixedProduct(693, "MAIZENA PTE 400 GR"),

fixedProduct(695, "MALETIN DE JAMON CEBO VILLAR 14X50GR"),
fixedProduct(696, "MANGO 1.40 PINTADO ROJO (BARATO)"),
fixedProduct(697, "MANZANILLA LA GUITA 0.375"),
fixedProduct(698, "MANZANILLA MUY FINA BARBADILLO 3/4","Comprando 12 unidades PRECIO OFERTA"),

fixedProduct(702, "MAYONESA PRIMA 400"),
fixedProduct(704, "MECHERO CLIPER TRANSPARENTE CAJA"),
fixedProduct(705, "MEJILLON CALVO ESCAB PACK3/80"),
fixedProduct(706, "MEJILLONES (20/30)RIA SULTAN PEQUEÑO DOP"),


fixedProduct(710, "MENTA POLEO LA BARRACA 10 INF."),
fixedProduct(711, "MERMELADA FRESA LA VIEJA FABRICA 350GR"),
fixedProduct(712, "MERMELADA MELOCOTON LA VIEJA FABRICA 350GR"),
fixedProduct(713, "MIEL LA DULCE ABEJA 1KG"),
fixedProduct(721, "MOJAMA ATUN USISA KG"),

fixedProduct(743, "NUEZ MOSCADA LA BARRACA BTE PEQUEÑO"),

fixedProduct(746, "ÑORAS SECAS LA BARRACA"),
fixedProduct(747, "OREGANO HOJA LA BARRACA BOTE"),
fixedProduct(748, "PACHARAN ZOCO 1 L."),
fixedProduct(750, "PALOMITA CARAMELO FAM 16U"),
fixedProduct(751, "PALOMITA CHOCO BLANCO FAM 16U"),
fixedProduct(752, "PALOMITA CHOCO FAM 16U"),

fixedProduct(756, "PAN RALLADO PANAERAS AJO/PEREJIL 300"),

fixedProduct(759, "PAPEL FILMS MERCASUR 30 M"),
fixedProduct(761, "PAPEL PARAFINADO"),
fixedProduct(762, "PASARRATOS SUPER SENIOR XXL 10U"),
fixedProduct(788, "PAÑUELOS RENOVA P-6"),

fixedProduct(790, "PECHUGA PAVO BRASEADA CAMPOFRIO KG"),
fixedProduct(792, "PECHUGA POLLO EXTRAJUGOSA L/80"),
fixedProduct(793, "PEDRO XIMENEZ 3 PASAS"),
fixedProduct(794, "PEPINILLOS DELICIAS 360 GR"),
fixedProduct(797, "PEREJIL LA BARRACA BTE PEQUEÑO"),
fixedProduct(798, "PET 1/2 FANTA NARANJA"),
fixedProduct(799, "PET 1/2 L NESTEA"),
fixedProduct(800, "PET 1/2 L NESTEA MARACUYA"),

fixedProduct(805, "PIÑA JUGO EXT DIAMIR P3 227"),
fixedProduct(806, "PIMENTON DULCE 1/8 LA BARRACA-LATA-"),
fixedProduct(807, "PIMENTON PICANTE BARRACA"),
fixedProduct(808, "PIMIENTA NEGRA GRANO LA BARRACA BTE PEQUEÑO"),

fixedProduct(810, "PIMIENTO MORRON EXTRA P-3"),



fixedProduct(814, "PINZA PLASTICO 24U"),



fixedProduct(827, "PLATO LLANO"),
fixedProduct(829, "PONCHE CABALLERO 1L"),
fixedProduct(830, "POPITAS MANTEQUILLA MICRO BORGES 100 MICRO"),
fixedProduct(831, "POPITAS UNIDAD BORGES 100 MICRO"),
fixedProduct(834, "PROTOS CRIANZA 201"),
fixedProduct(835, "P.TRAN (80004) 4 8X200"),
fixedProduct(836, "PUNTOMATIC COLOR TUBO 8 UND."),
fixedProduct(837, "PUNTOMATIC TUBO 4 DOSIS BLANCO"),
fixedProduct(838, "Q. APOLONIO ARTESANO CURADO"),
fixedProduct(839, "QUESO APOLONIO SEMI SIN LACTOSA KG"),

fixedProduct(841, "QUESO BARUS GARCIA BAQUERO KG"),
fixedProduct(842, "QUESO CABRA L/80 G NAVIDUL 2€"),

fixedProduct(849, "QUESO KIKO PLUS JUN.30 UNID"),




fixedProduct(854, "QUESO PORCIONES CASERIO 8/U"),

fixedProduct(859, "QUESO VIEJO MEZCLA LEVASA KG"),
fixedProduct(860, "QUITAMANCHAS ESPECIAL ROPA PULVERIZADOR KIRIKO"),

fixedProduct(863, "RALLADO OGGI FUNDIR PARA PASTA 200G"),
fixedProduct(864, "RALLADO VERDE PASTA HOCHLAND 50 G SEVILLANA"),
fixedProduct(865, "RAMON BILBAO CRIANZA 2013 75CL"),
fixedProduct(866, "RECAM MOPA PLA ATRAPAPOLVO 20 UN DESECH"),
fixedProduct(867, "RECOGEDOR C/MANGO"),
fixedProduct(872, "REMOLACHA CONSEMUR RALLADA TARRO S/370"),
fixedProduct(877, "RIOJA T BERONIA CRIANZA 3/4"),
fixedProduct(879, "ROLLO COCINA RENOVA PACK 2"),
fixedProduct(880, "ROLLO DE CARNE MECHADA KG CABO"),
fixedProduct(881, "ROLLOS PESOS 57 x 55"),
fixedProduct(882, "ROLLOS TPV 57 x 35"),
fixedProduct(883, "ROLLO TPV 80 x 80"),
fixedProduct(884, "ROMERO LA BARRACA"),



fixedProduct(892, "RON NEGRITA 1 L"),
fixedProduct(900, "SALCHICHAS CAMPESAN PACK 3 CAMPOF."),

fixedProduct(902, "SALCHICHAS JAMON CAMPOF.PACK 3"),
fixedProduct(903, "SALCHICHAS JUMBO CLASSIC OM 350G 14U"),
fixedProduct(904, "SALCHICHAS PAVO 6 UN.CAMPOF.140 GR"),
fixedProduct(905, "SALCHICHAS POLLO 6 UN.CAMPOF.140 G"),
fixedProduct(909, "SALCHICHON CUMBRE REAL CAMPOF."),

fixedProduct(913, "SALITO AZUL UNIDAD"),
fixedProduct(914, "SALITO ROJO UNIDAD"),
fixedProduct(915, "SALSA ALIOLI MONTEALBOR 180ML"),


fixedProduct(918, "SALSA GAUCHA BOCABAJO 300ML"),

fixedProduct(922, "SALSA YBARRA ALI-OLI 225"),
fixedProduct(923, "SALSA YBARRA ALI-OLI BOTE"),
fixedProduct(924, "SALSA YBARRA COCKTAIL 450 ML."),

fixedProduct(926, "SARDINAS ACEITE F.A 90G"),
fixedProduct(927, "SARDINAS TOMATE F.A 90G"),
fixedProduct(928, "SAZONADOR CARNE LA BARRACA PEQUEÑOS"),
fixedProduct(929, "SAZONADOR DE CARACOLES LA BARRACA"),
fixedProduct(930, "SAZONADOR POLLO LA BARRACA BOTE"),
fixedProduct(931, "SERVILLETA CELIA 30X30 MORADA"),





fixedProduct(946, "SUAV FLOR 2.2L 44D AZUL"),

fixedProduct(950, "SUAV SAN 1.29L CELESTE"),
fixedProduct(951, "SUAV SAN 1.29L ESENCIAS PARA RECORDAR"),
fixedProduct(952, "SUAV SAN 1.29L TALCO ROSA"),

fixedProduct(954, "SUNNY 330 CL FLORIDA P-12"),


fixedProduct(959, "TE LA BARRACA 10U."),

fixedProduct(961, "TILA BARRACA 10U."),
fixedProduct(962, "TINTO MISIVA RIBERA DUERO 2023"),
fixedProduct(963, "TINTO RIOJA M CACERES3/4 CRIANZA"),

fixedProduct(967, "TOMATE ENTERO MARTINETE 400"),
fixedProduct(968, "TOMATE ENTERO MARTINETE 810"),
fixedProduct(969, "TOMATE FRITO FRUCO/APIS"),
fixedProduct(976, "TOMATE TRITURADO APIS 800"),
fixedProduct(978, "TOMILLO LA BARRACA"),
fixedProduct(979, "TORTAS ACEITE I ROSALES 4UN C/10"),
fixedProduct(980, "TOSTAITOS SEVILLANAS 100 G X 10"),

fixedProduct(986, "TRISKYS FAM 16U"),
fixedProduct(989, "VASO 200 C 50UNI"),
fixedProduct(991, "VASO DE TUBO IRROMPIBLE"),
fixedProduct(992, "VASO MACETA"),
fixedProduct(993, "VASO POREX 7 OZ 200CC B/50"),

fixedProduct(999, "VINAGRE GOURMET JEREZ BOT 250ML"),
fixedProduct(1000, "VINAGRE GOURMET MANZANA 1 L"),
fixedProduct(1001, "VINAGRE GOURMET MODENA BOT 250 ML"),



fixedProduct(1008, "VINO BLANCO ELEGIDO 1L"),
fixedProduct(1010, "VINO CANASTA CREAM 75 CL"),
fixedProduct(1011, "VINO COCINA EL GUISO 0.70 C."),
fixedProduct(1013, "VINO SOLERA 1847 3/4"),

fixedProduct(1016, "VINO TINTO ELEGIDO 1L"),
fixedProduct(1017, "VINO TINTO EMILIO MORO 2022 75CL"),
fixedProduct(1018, "VINO TINTO PROTOS COSECHA 3/4"),
fixedProduct(1019, "VINO TINTO SOLDEPEÑAS 1 L."),
fixedProduct(1021, "VINO VERDEJO BELAROSSA 75 CL"),
fixedProduct(1022, "VIVO GATO BOCADITO POLLO LT 415G"),
fixedProduct(1023, "VIVO GATO BUEY 415G"),
fixedProduct(1024, "VIVO PERRO POLLO LT 830"),

fixedProduct(1027, "VODKA CIROC APLLE 0.7"),

fixedProduct(1044, "YOGO ICE 10UDS","Por 1 caja REGALO 2 unidades"),
fixedProduct(1045, "ZAMBA FRUTAS SURTIDAS P10"),


fixedProduct(1055, "ZUMO JUVER PIÑA 850ML"),

];

export default hiddenProductsRaw;
